import requests
import pytest

from conftest import get_film_posters
from constants import BASE_URL


class TestMovies:
    def test_movies_get_positive(self, get_film_posters):
        # Получаем афиши фильмов по параметрам
        film_posters = requests.get(f"{BASE_URL}/movies{get_film_posters}")
        assert film_posters.status_code == 200, "Ошибка при получении афиш фильмов"
        assert "count" in film_posters.json()
        assert "page" in film_posters.json()
        assert "pageSize" in film_posters.json()
        assert "pageCount" in film_posters.json()

    @pytest.mark.parametrize(
        "invalid_parameter",
        [
            "?pageSize=-1",
            "?pageSize=2147483648",
            "?pageSize=2147483648-1",
            "?pageSize=qwerty",
            "?pageSize=1.5",
            "?pageSize=None",
            "?pageSize=NULL",
            "?pageSize= ",
            "?pageSize=",
            '?pageSize=<script>alert("XSS")</script>&pageSize=2147483647',
            '?pageSize=<img src="x" onerror="alert("XSS")">',
            "?pageSize=<svg onload=alert(1)>",
            '?pageSize=javascript:alert("XSS")',
            "?pageSize=null",
            "?pageSize=-",
            "?pageSize=+",
            "?pageSize=*",
            "?pageSize=/",
            "?pageSize=]",
            "?pageSize=[",
            "?pageSize=(",
            "?pageSize==",
            "?pageSize=_",
            "?pageSize=&",
            "?pageSize=^",
            "?pageSize=%",
            "?pageSize=$",
            "?pageSize=#",
            "?pageSize=@",
            "?pageSize=!",
            "?pageSize=~",
            "?pageSize=`",
            "?pageSize=ё",
            "?pageSize=M12",
            "?pageSize={",
            "?pageSize=}",
            "?pageSize=;",
            "?pageSize=:",
            "?pageSize=.",
            "?pageSize=,",
            "?pageSize=<",
            "?pageSize=>",
            "?pageSize=|",
            "?pageSize=?",
            '?pageSize="""',
            '?pageSize=""',
            "?pageSize=" "",
            "?page=" "",
            "?page=0",
            "?page=922337203685477568",
            "?page=a",
            "?page=б",
            "?page=`",
            "?page=~",
            "?page=!",
            "?page=@",
            "?page=#",
            "?page=№",
            "?page=$",
            "?page=%",
            "?page=^",
            "?page=&",
            "?page=*",
            "?page=(",
            "?page=)",
            "?page=_",
            "?page=-",
            "?page=+",
            "?page==",
            "?page=|",
            "?page=/",
            "?page=]",
            "?page=[",
            "?page=}",
            "?page={",
            "?page=" "",
            '?page="',
            "?page=;",
            "?page=:",
            "?page=1:3",
            "?page=?",
            "?page=.",
            "?page=>",
            "?page=,",
            "?page=<",
            "?page=",
            "?page= ",
            "?minPrice=-1",
            "?minPrice=922337203685477568",
            "?minPrice=a",
            "?minPrice=б",
            "?minPrice=`",
            "?minPrice=~",
            "?minPrice=!",
            "?minPrice=@",
            "?minPrice=№",
            "?minPrice=$",
            "?minPrice=%",
            "?minPrice=^",
            "?minPrice=*",
            "?minPrice=(",
            "?minPrice=)",
            "?minPrice=_",
            "?minPrice=-",
            "?minPrice==",
            "?minPrice=|",
            "?minPrice=/",
            "?minPrice=]",
            "?minPrice=[",
            "?minPrice=}",
            "?minPrice={",
            '?minPrice="',
            "?minPrice=;",
            "?minPrice=:",
            "?minPrice=1:3",
            "?minPrice=?",
            "?minPrice=.",
            "?minPrice=>",
            "?minPrice=,",
            "?minPrice=<",
            "?minPrice=ABCDEF",
            "?minPrice=1000&maxPrice=1000",
            "?minPrice=1000&maxPrice=999",
            "?maxPrice=-1",
            "?maxPrice=922337203685477568",
            "?maxPrice=a",
            "?maxPrice=б",
            "?maxPrice=`",
            "?maxPrice=~",
            "?maxPrice=!",
            "?maxPrice=@",
            "?maxPrice=№",
            "?maxPrice=$",
            "?maxPrice=%",
            "?maxPrice=^",
            "?maxPrice=*",
            "?maxPrice=(",
            "?maxPrice=)",
            "?maxPrice=_",
            "?maxPrice=-",
            "?maxPrice==",
            "?maxPrice=|",
            "?maxPrice=/",
            "?maxPrice=]",
            "?maxPrice=[",
            "?maxPrice=}",
            "?maxPrice={",
            '?maxPrice="',
            "?maxPrice=;",
            "?maxPrice=:",
            "?maxPrice=1:3",
            "?maxPrice=?",
            "?maxPrice=.",
            "?maxPrice=>",
            "?maxPrice=,",
            "?maxPrice=<",
            "?maxPrice=ABCDEF",
            "?locations=-1",
            "?locations=922337203685477568",
            "?locations=a",
            "?locations=б",
            "?locations=`",
            "?locations=~",
            "?locations=!",
            "?locations=@",
            "?locations=#",
            "?locations=№",
            "?locations=$",
            "?locations=%",
            "?locations=^",
            "?locations=&",
            "?locations=*",
            "?locations=(",
            "?locations=)",
            "?locations=_",
            "?locations=-",
            "?locations=+",
            "?locations==",
            "?locations=|",
            "?locations=/",
            "?locations=]",
            "?locations=[",
            "?locations=}",
            "?locations={",
            "?locations=" "",
            '?locations="',
            "?locations=;",
            "?locations=:",
            "?locations=1:3",
            "?locations=?",
            "?locations=.",
            "?locations=>",
            "?locations=,",
            "?locations=<",
            "?locations=ABCDEF",
            "?genreId=-1",
            "?genreId=2147483648",
            "?genreId=a",
            "?genreId=б",
            "?genreId=`",
            "?genreId=~",
            "?genreId=!",
            "?genreId=@",
            "?genreId=№",
            "?genreId=$",
            "?genreId=%",
            "?genreId=^",
            "?genreId=*",
            "?genreId=(",
            "?genreId=)",
            "?genreId=_",
            "?genreId=-",
            "?genreId==",
            "?genreId=|",
            "?genreId=/",
            "?genreId=]",
            "?genreId=[",
            "?genreId=}",
            "?genreId={",
            '?genreId="',
            "?genreId=;",
            "?genreId=:",
            "?genreId=1:3",
            "?genreId=?",
            "?genreId=.",
            "?genreId=>",
            "?genreId=,",
            "?genreId=<",
            "?genreId=ABCDEF",
            "?createdAt=-1",
            "?createdAt=922337203685477568",
            "?createdAt=a",
            "?createdAt=б",
            "?createdAt=`",
            "?createdAt=~",
            "?createdAt=!",
            "?createdAt=@",
            "?createdAt=№",
            "?createdAt=$",
            "?createdAt=%",
            "?createdAt=^",
            "?createdAt=*",
            "?createdAt=(",
            "?createdAt=)",
            "?createdAt=_",
            "?createdAt=-",
            "?createdAt==",
            "?createdAt=|",
            "?createdAt=/",
            "?createdAt=]",
            "?createdAt=[",
            "?createdAt=}",
            "?createdAt={",
            '?createdAt="',
            "?createdAt=;",
            "?createdAt=:",
            "?createdAt=1:3",
            "?createdAt=?",
            "?createdAt=.",
            "?createdAt=>",
            "?createdAt=,",
            "?createdAt=<",
            "?createdAt=ABCDEF",
        ],
    )
    def test_movies_get_negative(self, invalid_parameter):
        # Получаем афиши фильмов по параметрам
        film_posters = requests.get(f"{BASE_URL}/movies{invalid_parameter}")
        print(f"{BASE_URL}/movies{invalid_parameter}")
        assert (
            film_posters.status_code == 400
        ), "С невалидными данными ожидается статус 400"
        assert "message" in film_posters.json()
        assert "error" in film_posters.json()
        assert "statusCode" in film_posters.json()
